### ISSUE TITLE
Opening intel links

### ISSUE THREAD

**Issue by Gollam** [IITC-CE/ingress-intel-total-conversion#297]
Is it possible to add the intent filters to open intel links, like in the old IITC?

https://github.com/iitc-project/ingress-intel-total-conversion/blob/master/mobile/AndroidManifest.xml#L55

**Comment by johnd0e** [comment]
Please describe what exact issue do you have with current intel filters.

**Comment by Gollam** [comment]
Currently, the intent filters defined are for "intel.ingress.com", but many tools still use the old format ("ingress.com/intel") which redirects to the new domain of course, but IITC-CE does not get offered to open those links.

**Comment by johnd0e** [comment]
Please check https://iitc.modos189.ru/build/test/IITC_Mobile-test.apk

**Comment by Gollam** [comment]
Strange, because it should've worked like that, but it does not. I'll do some further testing.

**Comment by Gollam** [comment]
Ok, the problem was that the tool I tested with uses "www.ingress.com/intel" :D That's why it worked with "*.ingress.com/intel". Also, I'd consider filtering for http as well, they will redirect that anyways.

**Comment by johnd0e** [comment]
New test build pushed.
Please confirm which of the following urls opened in app.

1. https://ingress.com/intel
2. https://www.ingress.com/intel
3. ~https://ingress.ingress.com/~
   https://intel.ingress.com/
4. ~https://ingress.ingress.com/intel~
   https://intel.ingress.com/intel

**Comment by Gollam** [comment]
All of them, except the 3rd one of course, because of the prefix. Good enough for me :) Thanks!

**Comment by johnd0e** [comment]
Well, I meant https://intel.ingress.com/
Please check

**Comment by Gollam** [comment]
Ok, now I see that you already had an intent filter for that as well, which should match. Strangely, that one still does not seem to work.

**Comment by johnd0e** [comment]
As per [docs](https://developer.android.com/guide/topics/manifest/data-element.html) 'All the <data> elements contained within the same <intent-filter> element contribute to the same filter.'

It's not good at all.

**Comment by Gollam** [comment]
I tested it some more, and now it does not offer IITC-CE for the 3rd or 4th, but it seems to work for a complete intel link, e.g.: https://intel.ingress.com/intel?ll=46.362646,23.38073&z=17&pll=46.362646,23.38073

So maybe Android does not suggest it everytime?

**Comment by johnd0e** [comment]
@Gollam 4. should be https://intel.ingress.com/intel

**Comment by Gollam** [comment]
Yeah, you're right :D Ok, so intel.ingress.com on it's own does not work because that is intended, according to the documentation. I understand now. So the solution is to create separate filters?

**Comment by johnd0e** [comment]
Test build updated, please check again

Also:
5. https://ingress.com/abc
6. https://www.ingress.com/abc

**Comment by Gollam** [comment]
All 6 is working :)

**Comment by johnd0e** [comment]
Oops. New build. Check these urls:

1.1. https://ingress.com/intel
1.2. https://www.ingress.com/intel
1.3. https://ingress.com/abc
1.4. https://www.ingress.com/abc
1.5. https://abc.ingress.com/intel
2.1. https://intel.ingress.com/
2.2. https://intel.ingress.com/intel
2.3. https://abc.ingress.com/

**Comment by Gollam** [comment]
1.1 works
1.2 works
1.3 doesn't work
1.4 doesn't work
1.5 doesn't work
2.1 works
2.2 works
2.3 doesn't work

**Comment by MysticJay** [comment]
1.2 should not work either

**Comment by johnd0e** [comment]
@MysticJay Explain please

**Comment by johnd0e** [comment]
@Gollam 
> I'd consider filtering for http as well

Please check in updated build

1.1. http://ingress.com/intel
1.2. http://www.ingress.com/intel
2.1. http://intel.ingress.com/

**Comment by MysticJay** [comment]
The official intel page is https://intel.ingress.com 
All other "currently still working" URLs will cause trouble sooner or later as they are redirected at NIA and they will drop that without any prior notice.
So if old plugins need adjustment, do so now - instead of continuing to support the depricated schemes.

**Comment by Gollam** [comment]
@johnd0e all working, thanks
@MysticJay what kind of trouble do you think it would cause?

**Comment by MysticJay** [comment]
e.g redirection loops, new and old tools that continue to use the old schemes or even invent new ones, because "they just work".

We should not support anything that the official page does not generate by it self.
The "/intel"-Links are officially only used to share "intel draws" and Map Coordinates

Fix your plugins and tools!

**Comment by MysticJay** [comment]
After I found about 30 different schemes used in 150 plugins I investigated the situation, because some plugins refused to work after using the official intel-Link. Since then I have been forwarding this on various channels and chats:
***************************************************
@All IITC Developers
after reports of malfunctioning plugins, I found that NIA changed the way how URLs get resolved on intel.ingress.com and they also changed the MAP-Link on www.ingress.com to now use https://intel.ingress.com. Additionally they are now using some paths which are not covered by the current URL-scheme. 
While the old style with an appended /intel* still works, it does not cover those paths that are already in use. Also NIA might remove this "redirection" in future. 

I conferenced with some others and this is the conclusion:

To cover the changed MAP-Link, and the changed url-scheme we recommend to remove all @match and @include lines and replace by only
// @match         https://intel.ingress.com/*
Sidenote 1 : a simple @match statement is sufficent, an additional @include is not needed
Sidenote 2 : /missions/* will be covered by the above statement as well, so these lines can be removed safely too.
*************************************

**Comment by Gollam** [comment]
I am convinced BTW, but the bug with the multiple data nodes still need to be fixed.
