### ISSUE TITLE
More cases to request write storage permissions

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#34]
> Request write storage permissions only if you add scripts.

When I open *.user.js at Chrome webpage (or in file manager) it proposes list of applications.
I select IITC and after confirmation all seems ok, but then `Plugins settings` screen appears without user plugins.

There should be permission request, I suppose.

And I think this even will not be enough, consider this case:
IITC was once installed and we have user plugins in `IITC-Mobile/plugins` directory.
Then we uninstall apk, and install it again.
Will we get permission request?

_Originally posted by @johnd0e in https://github.com/IITC-CE/ingress-intel-total-conversion/issues/4#issuecomment-446499237_

**Comment by modos189** [comment]
> And I think this even will not be enough, consider this case:
IITC was once installed and we have user plugins in IITC-Mobile/plugins directory.
Then we uninstall apk, and install it again.
Will we get permission request?

I thought read permissions were now set to default. Turns out not.
Old external userscripts will not be shown until the permissions are granted (for example, by adding a new script).
