### ISSUE TITLE
Portal history: Ingress's newly-released layers for explorer and pioneer activity

### ISSUE THREAD

**Issue by lollercopter** [IITC-CE/ingress-intel-total-conversion#434]
The generic Ingress Intel map now shows a player's visited (explorer) and captured (pioneer) portals using two filters: https://community.ingress.com/en/discussion/13451/portal-history-now-available-on-intel-map

Currently, this feature is not working in IITC. Could you add a feature for these layers? Thanks!

**Comment by MysticJay** [comment]
@le-jeu :
```
function summaryPortalData(a) {
return {
level: a[4],
health: a[5],
resCount: a[6],
image: a[7],
title: a[8],
ornaments: a[9],
mission: a[10],
mission50plus: a[11],
artifactBrief: parseArtifactBrief(a[12]),
timestamp: a[13],
visited: (a[18] & 1) === 1,
captured: (a[18] & 2) === 2,
scanned: (a[18] & 4) === 4,
};
};
```

**Comment by MysticJay** [comment]
Changing SUMMARY_PORTAL_DATA_LENGTH is wrong and so is the above snip.

We have
summary portal details (14)
detailed portal details (+4) 
extended portal detail (+1)

Thus portalDetails returned can be 14, 18 or 19

The xtende portal Details need to be parsed in `window.decodeArray.portalDetail`

**Comment by lollercopter** [comment]
Here is the first plugin:

https://github.com/EisFrei/IngressPortalHistoryFlags

I would like to see less clutter on the map though. Maybe change the orange/blue/green portal markers to a alternating orange/blue/green and red/purple color (changing the color every 45 degrees around the circle)?

Also, a portal capture counts as a portal visit. Therefore, the purple dot is redundant if the red dot is there.

**Comment by Eccenux** [comment]
You should probably merge this with uniques plugin. Just use this data to merge with what user selects. Same as using plexts for marking portals as captured.

Storing this data allows to show state when zoomed out. So that would be better then what Intel has.

Also having user's state allows to correct niantic bugs. I have a portal which I captured almost daily when going to work. And it's marked as not captured.

Conflict resolution of state:

* User captured, niantic not -> captured
* Niantic captured, user not -> captured

Etc.

**Comment by MysticJay** [comment]
Attention!
At the moment 'scanned' layer is wrongly titled as 'Scout Controlled' in stock intel!

- **"Scout Controller"** is a volatile status, that the agent looses sooner or later on interaction of other agents with the same portal.
- **"scanned"** is a permanent status, set when the agent submits the first 3D-Scan of a portal.
