### ISSUE TITLE
what show map 

### ISSUE THREAD

**Issue by sp00ck** [IITC-CE/ingress-intel-total-conversion#570]
I'm not have google and facebook account
how I can see map?

**Comment by le-jeu** [comment]
@sp00ck The same way as you do when you log in with stock intel (without iitc) : https://intel.ingress.com

**Comment by elkuku** [comment]
How do you log in to Ingress?

**Comment by sp00ck** [comment]
@elkuku @le-jeu 
this is problem, apple not appear in intel and if anybody have apple account cant use this program

**Comment by McBen** [comment]
Apple login is not supported by ingress intel. Feel free to contact the  [ingress support](https://ingress.com/support)

> This site and the scripts are not officially affiliated with Ingress or Niantic Labs.

**Comment by sp00ck** [comment]
If it's not an official program then why log in at all?
wouldn't it be better to make it so everyone can watch everything?

**Comment by crystalwizard** [comment]
> I'm not have google and facebook account how I can see map?

have you considered setting up a google account as well as your apple account? That way you'd have a way to log in that niantic accepts.

**Comment by caderoux** [comment]
> If it's not an official program then why log in at all? wouldn't it be better to make it so everyone can watch everything?

Intel currently requires login.  Several intel features depend on your account, such as alerts, faction COMM, inventory (C.O.R.E.), code redemption.  While it might be possible to consider a public anonymous intel which doesn't have those features, that would be up to Niantic to allow reduced feature set for unauthenticated users.

Because intel (with or without IITC) does not currently support Apple logins, you need to link a Google or Facebook account to your Ingress account.  And you would need to do this with vanilla intel or with IITC.

Separate from viewing the intel map, you already need to do this in order to redeem any codes from Niantic, either medal or gear codes.  Apple does not allow code redemption on their platform (because it bypasses the store).

**Comment by sp00ck** [comment]
But why should you wait? just make a map of portals and links. nothing more is needed. those users who are there and browse the map are enough. just make available what others have already downloaded.
that's as much as a cache

one big cache for everyone

**Comment by le-jeu** [comment]
You miss the point. IITC is only an overlay to improve how https://intel.ingress.com is rendered in a browser and allow some user customizations.

What you are asking is a map as an external service. While such thing will be hard to get up to date from player only, this is completly forbidden by niantic.(and I'm skipping the infrastructure needed for this)

"Just make map of portals and links" is already what https://intel.ingress.com is.
Just get a google/account, instead of asking the community of IITC users to become a scrapping tool.

**Comment by le-jeu** [comment]
You miss the point. IITC is only an overlay to improve how https://intel.ingress.com is rendered in a browser. 

What you are asking is a map as an external service. While such thing will be hard to get up to date from player only, this is completly forbidden by niantic.

"Just make map of portals and links" is already what https://intel.ingress.com is.

Just get a google/account, instead of asking the community of IITC players to become a scrapping tool.

Le 29 juillet 2022 12:56:05 UTC, "Łukasz Marek" ***@***.***> a écrit :
