### ISSUE TITLE
Remove custom plugins from IITC Mobile

### ISSUE THREAD

**Issue by Eccenux** [IITC-CE/ingress-intel-total-conversion#624]
There doesn't seem to be a way to remove old/unwanted plugins in an Android app.

It would be nice to have an action to remove plugins in the plugin list or under long tap menu maybe.

**Comment by xscreach** [comment]
Workaround: 
* Use some file browser (e.g. "Files")
* Navigate to //IITC_Mobile/plugins on your internal storage
* Delete plugins you don't need

And that's it.

Warning: Plugins should be disabled in IITC first otherwise iitc will try to enable them and fail - that is only logged in debug console, but could slow down iitc startup.
