### ISSUE TITLE
IITC-CE does not appear at Github as fork of original ingress-intel-total-conversion

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#9]
E.g. we are unable to send direct PRs to https://github.com/iitc-project/ingress-intel-total-conversion/
Co-operation with other forks gets harder too.

**Comment by modos189** [comment]
In the original project 115 open PRs that no one to accept, because it is unlikely it is important.
Also, there are so many differences with other repositories that you can rarely do without merge conflicts.

On the other hand, as a separate repository GitHub allows you to search for the project, which I found very convenient in the long term.

**Comment by johnd0e** [comment]
Well, when I see outdated project at github, then at first I search more updated forks.

Anyway, I've got your point, thanks.
